version: "2"

services:

  app:
    build: .
    image: keboola/gooddata-provisioning
    tty: true
    command: bash
    volumes:
      - ./:/code

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c '/code/vendor/bin/phpunit -c /code/phpunit.xml.dist  $$TEST_PATH'
    volumes:
      - ./:/code
    environment:
      - TEST_PATH
      - TEST_GD_LOGIN
      - TEST_GD_PASSWORD
      - TEST_GD_BACKEND
      - TEST_GD_DOMAIN
      - TEST_GD_SSO_PROVIDER
      - TEST_GD_AUTH_TOKEN

  ci-tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c '
             sleep 10
             && ./tests.sh
             '
    environment:
      - TEST_GD_LOGIN
      - TEST_GD_PASSWORD
      - TEST_GD_BACKEND
      - TEST_GD_DOMAIN
      - TEST_GD_SSO_PROVIDER
      - TEST_GD_AUTH_TOKEN
